### ISSUE TITLE
xxxFragment extends AbsBaseFragment 问题：如果xxxFragment要继承BaseFragment咋办呢

### ISSUE THREAD

**Issue by ChessLuo** [pinguo-zhouwei/CustomAdapter#4]
如果xxxFragment要继承BaseFragment，然后要用你这库就要继承AbsBaseFragment，java不是单继承的吗？那咋办呢

**Comment by pinguo-zhouwei** [comment]
对的，是有这个问题，其实这个AbsBaseFragment只是我写的一个Base封装示例，项目中可以参照这个自己加一个继承自BaseFragment 的AbsBaseFragment。后面我再看一下有没有更好的解决方案
